project:
  type: default
  output-dir: out
  execute-dir: project   # force working dir to project root
  render:
    output-path: out     # force html and files directly into ./out/

format:
  html:
    toc: true
    number-sections: true
    code-fold: false
