project:
  type: default
  output-dir: out
  execute-dir: project   # force working dir to project root
  render:
    - "*.qmd"            # render all .qmd files (optional — can remove entirely if not needed)

format:
  html:
    toc: true
    number-sections: true
    code-fold: false

